FROM --platform=linux/x86_64 amazon/aws-for-fluent-bit@sha256:d64ffe4749003cc7f51e1f7949e2fda60ab0e03608539aff85eb492c2bf10e9b

ENV TZ='Asia/Tokyo'
COPY fluent-bit_custom-local.conf /fluent-bit/etc/fluent-bit_custom-local.conf
COPY inputs.conf /fluent-bit/etc/inputs.conf
COPY stream_processing-local.conf /fluent-bit/etc/stream_processing-local.conf
COPY parsers_custom.conf /fluent-bit/etc/parsers_custom.conf
COPY mod_record.lua /fluent-bit/etc/mod_record.lua
COPY add_tag.lua /fluent-bit/etc/add_tag.lua