FROM --platform=linux/x86_64 amazon/aws-for-fluent-bit@sha256:f1e422e4fb715b6ba545aef8b16849befe0dd20dcc58e1ea6ce61982cc30a8c1

ENV TZ='Asia/Tokyo'
COPY fluent-bit_custom-local.conf /fluent-bit/etc/fluent-bit_custom-local.conf
COPY inputs.conf /fluent-bit/etc/inputs.conf
COPY stream_processing-local.conf /fluent-bit/etc/stream_processing-local.conf
COPY parsers_custom.conf /fluent-bit/etc/parsers_custom.conf
COPY mod_record.lua /fluent-bit/etc/mod_record.lua
COPY add_tag.lua /fluent-bit/etc/add_tag.lua