EULA: "TRUE"
OP_PERMISSION_LEVEL: "4"
DIFFICULTY: "hard"
MAX_PLAYERS: "4"
ENABLE_COMMAND_BLOCK: "true"
HARDCORE: "true"
VERSION: "1.21"
TYPE: "PAPER"
PAPER_CHANNEL: "experimental"
PLUGINS_FILE: "/data/plugins.txt"
SEED: ""