name-template: '🍏 $RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What’s Changed
  $CHANGES


autolabeler:
  - label: feature
    branch:
      - '/^feat(ure)?[/-].+/'
  - label: bug
    branch:
      - '/fix[/-].+/'
  - label: chore
    branch:
      - '/^chore[/-].+/'
  - label: refactor
    branch:
      - '/(refactor|refactoring)[/-].+/'
  - label: documentation
    files:
      - '*.md'
  - label: app
    files:
      - 'app/**/*'
  - label: docker
    files:
      - 'Dockerfile'
      - 'Dockerfile.*'
      - '.dockerignore'
      - 'docker-compose.yaml'
  - label: github
    files:
      - '.github/**/*'
  - label: fluentbit
    files:
      - 'docker/fluentbit/**/*'
  - label: minecraft
    files:
      - 'docker/minecraft/**/*'
  - label: terraform
    files:
      - 'terraform/**/*'
  - label: keeping
    files:
      - 'terraform/keeping/**/*'
  - label: scheduling
    files:
      - 'terraform/scheduling/**/*'
  - label: modules
    files:
      - 'terraform/modules/**/*'
