version: "3.8"

services:
  mc:
    platform: linux/x86_64
    container_name: minecraft
    build:
      context: ./docker/minecraft
      dockerfile: Dockerfile.restore
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      WEBHOOK_PATH:
      S3_BUCKET_NAME:
      S3_PREFIX_NAME:
      WHITELIST: 05910308-229d-46bb-a466-e5574dba490c,6b4a177a-54ee-4dd6-a50b-d993503892c1,2fb94c76-d968-4f25-a7cc-91fdccd23868
      OPS: 05910308-229d-46bb-a466-e5574dba490c,6b4a177a-54ee-4dd6-a50b-d993503892c1,2fb94c76-d968-4f25-a7cc-91fdccd23868
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials:ro
      - ~/.aws/config:/root/.aws/config:ro
      # attach the relative directory 'data' to the container's /data path
      - log-data:/data
  fluent-bit:
    container_name: fluentbit
    depends_on: 
      - mc
    build: 
      context: ./docker/fluentbit
      dockerfile: Dockerfile.local
    volumes:
      - log-data:/data
    command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit_custom-local.conf"]
volumes:
  log-data: