version: "3.8"

services:
  mc:
    platform: linux/x86_64
    container_name: minecraft
    build:
      context: ./docker/minecraft
      dockerfile: Dockerfile.local
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "8080:8080"
    environment:
      VERSION: 1.21
      EULA: "TRUE"
      TYPE: PAPER
      PAPER_CHANNEL: experimental
      PLUGINS_FILE: "/data/plugins.txt"
      SEED: ""

      WEBHOOK_PATH:
      S3_BUCKET_NAME:
      S3_PREFIX_NAME:
      WHITELIST: 05910308-229d-46bb-a466-e5574dba490c,6b4a177a-54ee-4dd6-a50b-d993503892c1,2fb94c76-d968-4f25-a7cc-91fdccd23868,2cffa334-b882-41ba-8e83-0bb4cb0d8769
      OPS: 05910308-229d-46bb-a466-e5574dba490c,6b4a177a-54ee-4dd6-a50b-d993503892c1,2fb94c76-d968-4f25-a7cc-91fdccd23868,2cffa334-b882-41ba-8e83-0bb4cb0d8769
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials:ro
      - ~/.aws/config:/root/.aws/config:ro
      - log-data:/data
  fluent-bit:
    container_name: fluentbit
    depends_on: 
      - mc
    build: 
      context: ./docker/fluentbit
      dockerfile: Dockerfile.local
    volumes:
      - log-data:/data:ro
    command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit_custom-local.conf"]
volumes:
  log-data: