version: "3.8"

services:
  mc:
    container_name: minecraft
    build:
      context: ./docker/minecraft
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EURA: "TRUE"
      WEBHOOK_PATH:
      S3_BUCKET_NAME:
      S3_PREFIX_NAME:
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials:ro
      - ~/.aws/config:/root/.aws/config:ro
      # attach the relative directory 'data' to the container's /data path
      # - ./docker/minecraft:/data
  fluent-bit:
    container_name: fluentbit
    depends_on: 
      - mc
    build: 
      context: ./docker/fluentbit
      dockerfile: Dockerfile.local
    volumes:
      - ./app:/data
    command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit_custom-local.conf"]