FROM --platform=linux/x86_64 itzg/minecraft-server@sha256:9d3d3d2bf46c7dcbb31001078407b4555f7759869f3d35eda4cfe36d660899ce

ENV TZ=Asia/Tokyo

ENV VERSION="1.20.2"
ENV TYPE="SPIGOT"

WORKDIR /data

# install aws cli and cleanup
RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    unzip \
    tini \
    vim \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install -i /usr/local/aws-cli -b /usr/bin \
    && rm -rf awscliv2.zip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /data/aws

ENV PLUGINS_FILE="/data/plugins.txt"
COPY --chown=1000:1000 ./plugins.txt ./
COPY --chown=1000:1000 ./dynmap/configuration.txt plugins/dynmap/
COPY --chown=1000:1000 ./scripts /scripts
RUN chmod -R 755 /scripts

# ベースイメージのSIGTERMの挙動をオーバーライドし、自前のスクリプトを実行する
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/scripts/entrypoint-local.sh"]