FROM --platform=linux/x86_64 itzg/minecraft-server@sha256:52fa3bc8d56cb421f268f5a4f9d7cd12901d9384e0d324fab4eab1c6600f815e

ENV TZ=Asia/Tokyo

WORKDIR /data

# install aws cli and cleanup
RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    unzip \
    tini \
    vim \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install -i /usr/local/aws-cli -b /usr/bin \
    && rm -rf awscliv2.zip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /data/aws

COPY --chown=1000:1000 ./plugins.txt ./
COPY --chown=1000:1000 ./squaremap/*.yml plugins/squaremap/
COPY --chown=1000:1000 ./scripts /scripts
RUN chmod -R 755 /scripts

# ベースイメージのSIGTERMの挙動をオーバーライドし、自前のスクリプトを実行する
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/scripts/entrypoint-local.sh"]