name: Auto Label PR by Environment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'terragrunt/**'
      - 'terraform/**'

permissions:
  pull-requests: write
  contents: read

jobs:
  auto-label:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            terragrunt/**
            terraform/**

      - name: Analyze changes and set labels
        uses: actions/github-script@v7
        with:
          script: |
            const autoLabel = require('./scripts/github-actions/auto-label.js');
            
            const changedFiles = `${{ steps.changed-files.outputs.all_changed_files }}`.split(' ').filter(f => f);
            
            await autoLabel(github, context, changedFiles);
