name: Matrix Docker Build with Snyk Scan

on:
  pull_request:
    branches:
      - main
    paths:
      - 'docker/fluentbit/**'
      - 'docker/minecraft/**'
  push:
    branches:
      - main
    paths:
      - 'docker/fluentbit/**'
      - 'docker/minecraft/**'
env:
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  S3_PREFIX_NAME: ${{ secrets.S3_PREFIX_NAME }}
  WEBHOOK_PATH: ${{ secrets.WEBHOOK_PATH }}
permissions:
  actions: write
  contents: write
  pull-requests: write
  security-events: write

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: 'docker/fluentbit'
            dockerfile: 'docker/fluentbit/Dockerfile'
            tag: 'minecraft/fluentbit:latest'
            path: 'docker/fluentbit/**'
          - context: 'docker/minecraft'
            tag: 'minecraft/server:latest'
            path: 'docker/minecraft/**'
            dockerfile: 'docker/minecraft/Dockerfile'
          - context: 'docker/minecraft'
            tag: 'minecraft/server-restore:latest'
            path: 'docker/minecraft/**'
            dockerfile: 'docker/minecraft/Dockerfile.restore'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Check diff
        id: diff
        uses: technote-space/get-diff-action@v4.2.0
        with:
          PATTERNS: |
            ${{ matrix.path }}

      - name: Build Docker image
        if: steps.diff.outputs.diff
        run: |
          docker build -t ${{ matrix.tag }} ${{ matrix.context }} -f ${{ matrix.dockerfile }}
      - name: Run Snyk to check Docker image for vulnerabilities
        if: steps.diff.outputs.diff && github.event_name == 'pull_request'
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ matrix.tag }}
          args: --file=${{ matrix.dockerfile }}
      - name: Upload result to GitHub Code Scanning
        if: steps.diff.outputs.diff && github.event_name == 'pull_request'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
      - name: Scan the Docker image with Snyk
        if: steps.diff.outputs.diff && github.event_name == 'pull_request'
        continue-on-error: true
        id: snyk_scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          RESULT=$(snyk container test ${{ matrix.tag }} --file=${{ matrix.dockerfile }} --severity-threshold=high --fail-on=all)
          echo "result=${RESULT}" >> $GITHUB_OUTPUT
          snyk container monitor ${{ matrix.tag }} --file=${{ matrix.dockerfile }}
      - name: Create comment with output
        uses: actions/github-script@v3.2.0
        if: steps.diff.outputs.diff && github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `## \`${{ matrix.tag }}\`

            <details><summary>Snyk Vulnerability Scan Results</summary>
            
            \`\`\`${{ steps.snyk_scan.outputs.result }}\`\`\`

            </details>`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Login to Amazon ECR
        if: github.event_name == 'push'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'
      - name: Build and push Docker image
        if: steps.diff.outputs.diff && github.event_name == 'push'
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ matrix.tag }}
