name: drift

on:
  schedule:
    # At 06:00 PM JST
    - cron: "0 9 * * *"
env:
  SLACK_USERNAME: DriftDetectBot
  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  TF_VERSION: 1.4.1
  AWS_REGION: ap-northeast-1
permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  drift:
    name: Drift
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [
          terraform/scheduling,
          terraform/keeping
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ matrix.dir }}

      - name: Terraform Plan
        run: terraform plan
          -var "assume_role_arn=${{ secrets.AWS_IAM_ROLE_ARN }}"
          -detailed-exitcode
        working-directory: ${{ matrix.dir }}

      - name: Nothing Drift
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: Nothing Drift
          SLACK_COLOR: good

      - name: Detect Drift
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: Detect Drift
          SLACK_COLOR: danger