name: Force Apply and Push

on:
  push:
    branches:
      - main

env:
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  S3_PREFIX_NAME: ${{ secrets.S3_PREFIX_NAME }}
  WEBHOOK_PATH: ${{ secrets.WEBHOOK_PATH }}
  TF_VAR_WEBHOOK_PATH: ${{ secrets.WEBHOOK_PATH }}

permissions:
  id-token: write
  actions: write
  contents: write
  pull-requests: write
  security-events: write

jobs:
  force_apply_and_push:
    name: Force Apply and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/minecraft-test-github-actions
          role-session-name: github-actions-test-session
          aws-region: ap-northeast-1
        
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'
      - name: Force Apply for Schedule
        if: "${{ contains(github.event.pull_request.labels.*.name, 'target: schedule') }}"
        run: |
          cd terraform/scheduling
          cat << EOF > secrets.yaml
          OPS: ${{ secrets.WHITELIST_PLAYERS }}
          WHITELIST: ${{ secrets.WHITELIST_PLAYERS }}
          WEBHOOK_PATH: ${{ secrets.WEBHOOK_PATH }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_PREFIX_NAME: ${{ secrets.S3_PREFIX_NAME }}
          FILTERING_STRINGS: ${{ secrets.FILTERING_STRINGS }}
          EOF
          terraform init -lock=false
          terraform apply -lock=false -auto-approve
        shell: bash

      - name: Force Apply for Keeping
        if: "${{ contains(github.event.pull_request.labels.*.name, 'target: keeping') }}"
        run: |
          cd terraform/keeping
          terraform init -lock=false
          terraform apply -lock=false -auto-approve
        shell: bash

      - name: Docker Build and Push for Minecraft
        if: "${{ contains(github.event.pull_request.labels.*.name, 'target: minecraft') }}"
        run: |
          docker build -t minecraft/server:latest docker/minecraft -f docker/minecraft/Dockerfile
          docker tag minecraft/server:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/minecraft/server:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/minecraft/server:latest
          shell: bash
      - name: Docker Build and Push for Minecraft(restore)
        if: "${{ contains(github.event.pull_request.labels.*.name, 'target: minecraft-restore') }}"
        run: |
          docker build -t minecraft/server-restore:latest docker/minecraft -f docker/minecraft/Dockerfile.restore
          docker tag minecraft/server-restore:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/minecraft/server-restore:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/minecraft/server-restore:latest
          shell: bash

      - name: Docker Build and Push for Fluentbit
        if: "${{ contains(github.event.pull_request.labels.*.name, 'target: fluentbit') }}"
        run: |
          docker build -t minecraft/fluentbit:latest docker/fluentbit -f docker/fluentbit/Dockerfile
          docker tag minecraft/fluentbit:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/minecraft/fluentbit:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/minecraft/fluentbit:latest
          shell: bash