name: Release to release branch

on:
  release:
    types: [published]

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - run: git describe --abbrev=0 --tags > /tmp/version

      - run: git checkout -b release
      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          # installation-id: ${{ secrets.APP_INSTALLATION_ID }}
      - run: git push --force "https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }}" release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      # - uses: everlytic/branch-merge@1.1.2
      #   with:
      #     github_token: ${{ github.token }}
      #     source_ref: ${{ github.ref }}
      #     target_branch: 'release'
      #     commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
      # - run: git describe --abbrev=0 --tags > /tmp/version
      # - uses: actions/checkout@v3
      #   with:
      #     ref: release
      # - run: git config --global user.email "kounoike.yuusuke+github-autocommit@gmail.com"
      # - run: git config --global user.name "Auto-Release"
      # - run: git merge --allow-unrelated-histories ${{ github.ref }}
      # - run: mv /tmp/version .
      # - name: push
      #   uses: github-actions-x/commit@v2.6
      #   with:
      #     files: version
      #     github-token: ${{ github.token }}
      #     push-branch: 'release'
      #     force-add: 'true'
      #     commit-message: '[Automated] Merged release and add version file'
      #     name: Auto-release
      #     email: kounoike.yuusuke+github-autocommit@gmail.com