name: Start and Stop Workflow

on:
  schedule:
    # At 08:00 AM UTC
    - cron: '0 8 * * *'
    # At 08:00 PM UTC
    - cron: '0 20 * * *'
env:
  SLACK_USERNAME: DeployBot
  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  TF_VERSION: 1.4.1
  AWS_REGION: ap-northeast-1

jobs:
  scheduled_job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: terraform setup
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Run start.sh at 8 AM
      if: github.event.schedule == '0 8 * * *'
      run: |
        terraform init
        terraform apply -auto-approve

    - name: Run stop.sh at 8 PM
      if: github.event.schedule == '0 20 * * *'
      run: |
        terraform init
        terraform destroy -auto-approve

    - name: Slack Notification on Success
      uses: rtCamp/action-slack-notify@v2
      if: ${{ success() }}
      env:
        SLACK_TITLE: Deploy / Success
        SLACK_COLOR: good
        SLACK_MESSAGE: terraform command execution success🚀

    - name: Slack Notification on Failure
      uses: rtCamp/action-slack-notify@v2
      if: ${{ failure() }}
      env:
        SLACK_TITLE: Deploy / Failure
        SLACK_COLOR: danger
        SLACK_MESSAGE: terraform command execution failure😢