name: Terragrunt Scheduled Operations

on:
  # 一時無効化
  # schedule:
  #   # At 08:00 PM JST
  #   - cron: '0 11 * * 6,0'
  #   # At 02:00 AM JST
  #   - cron: '0 17 * * 6,0'
  repository_dispatch:
    types: [start, stop]

env:
  SLACK_USERNAME: TerragruntBot
  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  SLACK_WEBHOOK: https://hooks.slack.com/services/${{secrets.WEBHOOK_PATH}}
  TF_VAR_WEBHOOK_PATH: ${{ secrets.WEBHOOK_PATH }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  TERRAGRUNT_VERSION: 0.67.16
  TERRAFORM_VERSION: 1.9.8
  AWS_REGION: ap-northeast-1

jobs:
  scheduled_operations:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/minecraft-test-github-actions
        role-session-name: github-actions-terragrunt-scheduled
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup aqua
      uses: aquaproj/aqua-installer@v3.0.1
      with:
        aqua_version: v2.30.0

    - name: Install tools via aqua
      run: aqua install --all

    - name: Setup Terragrunt
      run: |
        curl -Lo terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.TERRAGRUNT_VERSION }}/terragrunt_linux_amd64
        chmod +x terragrunt
        sudo mv terragrunt /usr/local/bin/

    - name: Create Mapping Yaml
      working-directory: terraform/scheduling
      run: |
        cat << EOF > secrets.yaml
        OPS: ${{ secrets.WHITELIST_PLAYERS }}
        WHITELIST: ${{ secrets.WHITELIST_PLAYERS }}
        WEBHOOK_PATH: ${{ secrets.WEBHOOK_PATH }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        S3_PREFIX_NAME: ${{ secrets.S3_PREFIX_NAME }}
        FILTERING_STRINGS: ${{ secrets.FILTERING_STRINGS }}
        EOF

    - name: Start Minecraft Server (Schedule)
      if: github.event.schedule == '0 11 * * 6,0' 
      working-directory: terragrunt/environments/scheduling
      run: |
        echo "Starting Minecraft server via scheduled job..."
        terragrunt apply --terragrunt-non-interactive \
          -var set_recovery_point=false \
          -var set_seed_value=false \
          -auto-approve
      env:
        TF_VAR_aws_account_id: ${{ env.AWS_ACCOUNT_ID }}

    - name: Stop Minecraft Server (Schedule)
      if: github.event.schedule == '0 17 * * 6,0'
      working-directory: terragrunt/environments/scheduling
      run: |
        echo "Stopping Minecraft server via scheduled job..."
        terragrunt destroy --terragrunt-non-interactive -auto-approve
      env:
        TF_VAR_aws_account_id: ${{ env.AWS_ACCOUNT_ID }}

    - name: Execute Terragrunt on Repository Dispatch
      if: github.event_name == 'repository_dispatch'
      working-directory: terragrunt/environments/scheduling
      run: |
        if [ "${{ github.event.action }}" == "start" ]; then
          echo "Starting Minecraft server via repository dispatch..."
          terragrunt apply --terragrunt-non-interactive \
            -var set_recovery_point=false \
            -var set_seed_value=false \
            -auto-approve
        elif [ "${{ github.event.action }}" == "stop" ]; then
          echo "Stopping Minecraft server via repository dispatch..."
          terragrunt destroy --terragrunt-non-interactive -auto-approve
        fi
      env:
        TF_VAR_aws_account_id: ${{ env.AWS_ACCOUNT_ID }}

    - name: Slack Notification on Success
      uses: rtCamp/action-slack-notify@v2
      if: ${{ success() }}
      env:
        SLACK_TITLE: Terragrunt Operation / Success
        SLACK_COLOR: good
        SLACK_MESSAGE: "Terragrunt ${{ github.event.action || 'scheduled' }} operation completed successfully 🚀"

    - name: Slack Notification on Failure
      uses: rtCamp/action-slack-notify@v2
      if: ${{ failure() }}
      env:
        SLACK_TITLE: Terragrunt Operation / Failure
        SLACK_COLOR: danger
        SLACK_MESSAGE: "Terragrunt ${{ github.event.action || 'scheduled' }} operation failed 😢"
