name: PR Comment Job Example

permissions:
  contents: read

on:
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/test')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/github-script@v7
        id: set-target-branch
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            core.setOutput('base_ref', pr.base.ref);
            core.setOutput('head_ref', pr.head.ref);
      - name: Output refs
        run: |
          echo "Base ref: ${{ steps.set-target-branch.outputs.base_ref }}"
          echo "Head ref: ${{ steps.set-target-branch.outputs.head_ref }}"
      # - uses: actions/checkout@v4
      #   name: Checkout base branch
      #   with:
      #     fetch-depth: 100
      #     ref: ${{ steps.set-target-branch.outputs.base_ref }}

      - uses: actions/checkout@v4
        name: Checkout head branch
        with:
          fetch-depth: 0
          ref: ${{ steps.set-target-branch.outputs.head_ref }}

      - name: Check diff between base and head
        run: |
          files=($(git diff origin/${{ steps.set-target-branch.outputs.base_ref }}...HEAD --name-only | tr '\n' ' '))
          if [ ${#files[@]} -eq 0 ]; then
            echo "No changes detected."
            exit 0
          fi
          for file in "${files[@]}"; do
            echo "${file}"
          done