name: PR Comment Job Example

permissions:
  contents: read

on:
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/test')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/github-script@v6
        id: set-target-branch
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            core.setOutput('head_sha', pr.head.sha);
            core.setOutput('base_sha', pr.base.sha);

      - name: Output SHAs
        run: |
          echo "Base SHA: ${{ steps.set-target-branch.outputs.base_sha }}"
          echo "Head SHA: ${{ steps.set-target-branch.outputs.head_sha }}"

      - uses: actions/checkout@v4
        name: Checkout base commit
        with:
          fetch-depth: 1
          ref: ${{ steps.set-target-branch.outputs.base_sha }}

      - uses: actions/checkout@v4
        name: Checkout head commit
        with:
          fetch-depth: 1
          ref: ${{ steps.set-target-branch.outputs.head_sha }}

      - name: Check diff between base and head SHAs
        run: |
          files=($(git diff ${{ steps.set-target-branch.outputs.base_sha }} ${{ steps.set-target-branch.outputs.head_sha }} --name-only | tr '\n' ' '))
          for file in "${files[@]}"; do
            echo "${file}"
          done
