name: PR Comment Job Example

permissions:
  contents: read

on:
  issue_comment:
      types: [created]

jobs:
  check_before_merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout "${{ github.base_ref }}"
        with:
          fetch-depth: 1
          ref: ${{ github.base_ref }}
      - uses: actions/checkout@v4
        name: checkout "${{ github.head_ref }}"
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref}}
      - name: check_diff
        shell: bash
        run: |
          files=(`git diff origin/${{ github.base_ref }} --name-only|tr '\n' ' ' `)
          for file in ${files[@]}; do
            echo ${file}
          done