name: PR Comment Job Example

permissions:
  contents: read

on:
  issue_comment:
      types: [created]

jobs:
  pr_commented:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/test')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/github-script@v6
        id: set-target-branch
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const pull_request = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            return {head_ref: pull_request.data.head.ref, base_ref: pull_request.data.base.ref}
      - name: Output refs
        if: steps.set-target-branch.outputs.base_ref != ''
        run: |
          echo "Base ref: ${{ steps.set-target-branch.outputs.base_ref }}"
          echo "Head ref: ${{ steps.set-target-branch.outputs.head_ref }}"
      - uses: actions/checkout@v4
        name: checkout "${{ steps.set-target-branch.outputs.base_ref }}"
        with:
          fetch-depth: 1
          ref: ${{ steps.set-target-branch.outputs.base_ref }}
      - uses: actions/checkout@v4
        name: checkout "${{ steps.set-target-branch.outputs.head_ref }}"
        with:
          fetch-depth: 1
          ref: ${{ steps.set-target-branch.outputs.head_ref }}
      - name: check_diff
        shell: bash
        run: |
          files=(`git diff origin/${{ steps.set-target-branch.outputs.base_ref }} --name-only|tr '\n' ' ' `)
          for file in ${files[@]}; do
            echo ${file}
          done